import { Project, Skill, Service } from "./types";

export const BRAND_INFO = {
  name: "David Adeboyejo",
  brand: "VybzTech",
  titles: [
    "Product Engineer",
    "Full Stack Developer",
    "Frontend Engineer",
    "Software Engineer",
    "Mobile Developer",
  ],
  location: "📍 Remote",
  email: "adedave77@gmail.com",
  phone: "+234 812 182 0645",
  github: "https://github.com/VybzTech",
  linkedin: "https://linkedin.com/in/VybzTech",
  twitter: "https://twitter.com/djay_vybz",
  instagram: "https://instagram.com/vybz.tech",
};

export const PROJECTS: Project[] = [
  {
    id: 1,
    name: "Division Report Form",
    status: "completed",
    description: "A comprehensive reporting system built to streamline internal data collection and analysis.",
    tags: ["Frontend", "Form"],
    github: "https://github.com/VybzTech/Report-Form",
    link: "https://division-report-form.netlify.app",
    image: "/images/Projects/ADMIN-Page.png",
    role: "LIRS IT Support Intern",
    timeline: "3 Weeks",
    stack: ["HTML5", "CSS3", "JavaScript", "Bootstrap", "Jquery"],
    metrics: [
      { label: "Years Experience", value: "4+" },
      { label: "Projects Completed", value: "10+" },
    ],
  },
  {
    id: 2,
    name: "Graph Task Manager",
    status: "In-Progress",
    description: "Visual task management platform using graphical representations to analyze team performance.",
    tags: ["Data Vis", "PHP", "Chart.js"],
    github: "https://github.com/Dharvo/Task-Manager",
    link: "https://taskmanager-e694e.web.app",
    image: "/images/Projects/HOME.png",
    role: "LIRS IT Support Intern",
    timeline: "2 Months",
    stack: ["PHP", "ChartJS", "Ajax", "MySQL", "Bootstrap"],
  },
  {
    id: 3,
    name: "Netflex",
    status: "completed",
    description: "High-fidelity Netflix clone featuring dynamic content loading via TMDb API and Firebase integration.",
    tags: ["React", "Clone", "SaaS"],
    github: "https://github.com/Dharvo/Netflex",
    link: "https://netflex-eb4ee.web.app",
    image: "/images/Netflex-Project.png",
    role: "Lead Developer",
    timeline: "1 Month",
    stack: ["React", "Firebase", "Axios", "TMDb API", "CSS3"],
  },
  {
    id: 4,
    name: "Sammie's Art Gallery",
    status: "completed",
    description: "A premium digital gallery for a hyper-realistic portrait artist, featuring global commission handling.",
    tags: ["React", "Art", "E-commerce"],
    github: "https://github.com/Dharvo/my-portfolio",
    link: "https://sammie-art.web.app",
    image: "/images/Projects/Loading Page.png",
    role: "Product Designer & Developer",
    timeline: "Multiple Phases",
    stack: ["React", "SCSS", "Figma", "Firebase", "Material UI", "Swiper"],
  },
  {
    id: 5,
    name: "Wha'Todo App",
    status: "completed",
    description: "Mobile task management application with offline storage and advanced categorization.",
    tags: ["Mobile", "Flutter", "Productivity"],
    github: "https://github.com/Dharvo/Whatodo-App",
    link: "https://github.com/Dharvo/whatodo/raw/main/Wha'todo.apk",
    image: "/images/Projects/404 Page.png",
    role: "Mobile Developer",
    timeline: "10 Months",
    stack: ["Flutter", "Dart", "Hive", "Firebase", "Cubit"],
  },
  {
    id: 6,
    name: "PR. Photography",
    status: "completed",
    description: "Portfolio for a professional photographer, rebuilt with Next.js for extreme performance and SEO.",
    tags: ["Next.js", "Photography", "SEO"],
    github: "https://github.com/Dharvo/PR",
    link: "https://github.com/Dharvo/PR/",
    image: "/images/Projects/HOME – Dark Mode.png",
    role: "Full Stack Engineer",
    timeline: "8 Months",
    stack: ["Next.js", "React", "Firebase", "SCSS", "Adobe XD"],
  },
];

export const SKILLS: Skill[] = [
  { name: "React JS", level: 92, category: "frontend" },
  { name: "Next JS", level: 85, category: "frontend" },
  { name: "TypeScript", level: 80, category: "frontend" },
  { name: "Tailwind CSS", level: 94, category: "frontend" },
  { name: "JavaScript", level: 90, category: "frontend" },
  { name: "Node JS", level: 82, category: "backend" },
  { name: "ASP .NET Core", level: 75, category: "backend" },
  { name: "Flutter", level: 70, category: "frontend" },
  { name: "Figma", level: 74, category: "design" },
  { name: "Adobe XD", level: 93, category: "design" },
  { name: "Firebase", level: 88, category: "tools" },
  { name: "PostgreSQL", level: 78, category: "backend" },
];``

export const TITLES = [
  "Electronic & Computer Engineer",
  "Product Engineer",
  "Senior Front End Developer",
  "Full Stack Developer",
];

export const SERVICES: Service[] = [
  {
    name: "Frontend Engineering",
    description: "Building blazing fast, accessible, and premium user interfaces with modern frameworks.",
    icon: "Code",
  },
  {
    name: "Backend Systems",
    description: "Architecting scalable APIs and robust database schemas for complex applications.",
    icon: "Cpu",
  },
  {
    name: "Product Design",
    description: "Transforming ideas into high-fidelity prototypes and user-centric digital experiences.",
    icon: "FigmaLogo",
  },
];
