import { Project, Skill, Service } from "./types";

export const BRAND_INFO = {
  name: "David Adeboyejo",
  brand: "VybzTech",
  titles: [
    "Product Engineer",
    "Full Stack Developer",
    "Frontend Engineer",
    "Software Engineer",
    "Mobile Developer",
  ],
  location: "📍 Remote",
  location2: "📍 Lagos, NG",
  email: "adedave77@gmail.com",
  phone: "+234 812 182 0645",
  github: "https://github.com/VybzTech",
  linkedin: "https://linkedin.com/in/VybzTech",
  twitter: "https://twitter.com/djay_vybz",
  instagram: "https://instagram.com/vybz.tech",
};

export const PROJECTS: Project[] = [
  {
    id: 1,
    name: "Division Report Form",
    status: "completed",
    description: "A comprehensive reporting system built to streamline internal data collection and analysis.",
    fullContent: "The Division Report Form is a sophisticated reporting system that streamlines the data collection process for organizational divisions. Built with vanilla JavaScript and Bootstrap, it provides an intuitive interface for users to submit detailed reports with validation and analytics.",
    tags: ["Frontend", "Form"],
    github: "https://github.com/VybzTech/Report-Form",
    link: "https://division-report-form.netlify.app",
    image: "/images/Projects/ADMIN-Page.png",
    role: "LIRS IT Support Intern",
    timeline: "3 Weeks",
    stack: ["HTML5", "CSS3", "JavaScript", "Bootstrap", "Jquery"],
    metrics: [
      { label: "Years Experience", value: "4+" },
      { label: "Projects Completed", value: "10+" },
    ],
  },
  {
    id: 2,
    name: "Graph Task Manager",
    status: "In-Progress",
    description: "Visual task management platform using graphical representations to analyze team performance.",
    fullContent: "Graph Task Manager is an innovative platform that visualizes team tasks and performance metrics in real-time. Built with PHP backend and Chart.js for visualizations, it allows teams to track progress, identify bottlenecks, and optimize workflow efficiency.",
    tags: ["Data Vis", "PHP", "Chart.js"],
    github: "https://github.com/Dharvo/Task-Manager",
    link: "https://taskmanager-e694e.web.app",
    image: "/images/Projects/HOME.png",
    role: "LIRS IT Support Intern",
    timeline: "2 Months",
    stack: ["PHP", "ChartJS", "Ajax", "MySQL", "Bootstrap"],
  },
  {
    id: 3,
    name: "Netflex",
    status: "completed",
    description: "High-fidelity Netflix clone featuring dynamic content loading via TMDb API and Firebase integration.",
    fullContent: "Netflex is a production-grade Netflix clone built with React and Firebase. It features real-time content discovery through TMDb API, user authentication, personalized recommendations, and seamless streaming experience mirroring the industry standard.",
    tags: ["React", "Clone", "SaaS"],
    github: "https://github.com/Dharvo/Netflex",
    link: "https://netflex-eb4ee.web.app",
    image: "/images/Netflex-Project.png",
    role: "Lead Developer",
    timeline: "1 Month",
    stack: ["React", "Firebase", "Axios", "TMDb API", "CSS3"],
    metrics: [
      { label: "Movies Available", value: "1000+" },
      { label: "Users", value: "500+" },
    ],
  },
  {
    id: 4,
    name: "Sammie's Art Gallery",
    status: "completed",
    description: "A premium digital gallery for a hyper-realistic portrait artist, featuring global commission handling.",
    fullContent: "Sammie's Art Gallery is a premium e-commerce platform showcasing hyper-realistic portrait artwork. Built with React and Material UI, it provides seamless commission booking, payment processing, and global delivery coordination for a professional artist.",
    tags: ["React", "Art", "E-commerce"],
    github: "https://github.com/Dharvo/my-portfolio",
    link: "https://sammie-art.web.app",
    image: "/images/Projects/Loading Page.png",
    role: "Product Designer & Developer",
    timeline: "Multiple Phases",
    stack: ["React", "SCSS", "Figma", "Firebase", "Material UI", "Swiper"],
    metrics: [
      { label: "Commissions Completed", value: "50+" },
      { label: "Client Satisfaction", value: "98%" },
    ],
  },
  {
    id: 5,
    name: "Wha'Todo App",
    status: "completed",
    description: "Mobile task management application with offline storage and advanced categorization.",
    fullContent: "Wha'Todo is a feature-rich Flutter mobile application designed to revolutionize task management. Built with offline-first architecture, it empowers users to manage their productivity seamlessly with advanced categorization, smart reminders, and cloud synchronization through Firebase.",
    tags: ["Mobile", "Flutter", "Productivity"],
    github: "https://github.com/Dharvo/Whatodo-App",
    link: "https://github.com/Dharvo/whatodo/raw/main/Wha'todo.apk",
    image: "/images/Projects/404 Page.png",
    role: "Mobile Developer",
    timeline: "10 Months",
    stack: ["Flutter", "Dart", "Hive", "Firebase", "Cubit"],
    metrics: [
      { label: "Downloads", value: "500+" },
      { label: "Rating", value: "4.5★" },
    ],
  },
  {
    id: 6,
    name: "PR. Photography",
    status: "completed",
    description: "Portfolio for a professional photographer, rebuilt with Next.js for extreme performance and SEO.",
    fullContent: "PR. Photography is a high-performance portfolio website for a professional photographer. Built with Next.js for optimal SEO and lightning-fast page loads, it showcases stunning photography with smooth animations and seamless image optimization.",
    tags: ["Next.js", "Photography", "SEO"],
    github: "https://github.com/Dharvo/PR",
    link: "https://github.com/Dharvo/PR/",
    image: "/images/Projects/HOME – Dark Mode.png",
    role: "Full Stack Engineer",
    timeline: "8 Months",
    stack: ["Next.js", "React", "Firebase", "SCSS", "Adobe XD"],
    metrics: [
      { label: "PageSpeed Score", value: "98" },
      { label: "SEO Rank", value: "Top 10" },
    ],
  },
];

export const SKILLS: Skill[] = [
  // Original core skills
  { name: "React JS", level: 92, category: "frontend", image: "ReactJS.png" },
  { name: "Next JS", level: 85, category: "frontend", image: "Next-JS.svg" },
  { name: "TypeScript", level: 80, category: "frontend", image: "typescript.png" },
  { name: "Tailwind CSS", level: 94, category: "frontend", image: "TailwindCSS.png" },
  { name: "JavaScript", level: 90, category: "frontend", image: "JS.png" },
  { name: "Node JS", level: 82, category: "backend", image: "Node.png" },
  { name: "ASP .NET Core", level: 75, category: "backend", image: "DOTNET-1.svg" },
  { name: "Flutter", level: 70, category: "frontend", image: "Flutter.svg" },
  { name: "Figma", level: 74, category: "design", image: "Figma.png" },
  { name: "Adobe XD", level: 93, category: "design", image: "Adobe-XD.png" },
  { name: "Firebase", level: 88, category: "tools", image: "Firebase.png" },
  { name: "PostgreSQL", level: 78, category: "backend", image: "postgres.png" },
  // Additional tools (set to 50%)
  { name: "Android Studio", level: 50, category: "tools", image: "Android-studio.png" },
  { name: "Bootstrap", level: 50, category: "tools", image: "Bootstrap.png" },
  { name: "CSS3", level: 50, category: "tools", image: "CSS3.png" },
  { name: "Chartjs", level: 50, category: "tools", image: "Chartjs.svg" },
  { name: "DOTNET-1", level: 50, category: "tools", image: "DOTNET-1.svg" },
  { name: "Dart Logo", level: 50, category: "tools", image: "Dart-Logo.png" },
  { name: "DotNet Framework", level: 50, category: "tools", image: "DotNet-Framework.svg" },
  { name: "Github", level: 50, category: "tools", image: "Github.png" },
  { name: "HTML5", level: 50, category: "tools", image: "HTML5.png" },
  { name: "Jquery", level: 50, category: "tools", image: "Jquery.png" },
  { name: "Material UI", level: 50, category: "tools", image: "Material-ui.png" },
  { name: "Netlify", level: 50, category: "tools", image: "Netlify-Logo.png" },
  { name: "Php", level: 50, category: "tools", image: "Php.png" },
  { name: "SCSS", level: 50, category: "tools", image: "SCSS.png" },
  { name: "Swiper", level: 50, category: "tools", image: "Swiper.svg" },
  { name: "VS Code", level: 50, category: "tools", image: "VS-Code.png" },
  { name: "Visual Studio", level: 50, category: "tools", image: "Visual_Studio.png" },
  { name: "Youtube", level: 50, category: "tools", image: "Youtube.png" },
  { name: "C Sharp", level: 50, category: "tools", image: "c-sharp.png" }
];

export const TITLES = [
  "Electronic & Computer Engineer",
  "Product Engineer",
  "Senior Front End Developer",
  "Full Stack Developer",
];

export const SERVICES: Service[] = [
  {
    name: "Frontend Engineering",
    description: "Building blazing fast, accessible, and premium user interfaces with modern frameworks.",
    icon: "Code",
  },
  {
    name: "Backend Systems",
    description: "Architecting scalable APIs and robust database schemas for complex applications.",
    icon: "Cpu",
  },
  {
    name: "Product Design",
    description: "Transforming ideas into high-fidelity prototypes and user-centric digital experiences.",
    icon: "FigmaLogo",
  },
];
